In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr
from pycontrails import Fleet

In [113]:
# f = "../data/filed_meta.parquet"
# f = "../data/optimised_meta.parquet"

f = "../data/filed_trajectories_EAGWP100.parquet"
# f = "../data/optimised_trajectories_EAGWP100.parquet"

# f = "../data/filed_trajectories_EAGWP20.parquet"
# f = "../data/optimised_trajectories_EAGWP20.parquet"

# once with and once without CO2e
# f = "../data/filed_trajectories_ATR100.parquet"
# f = "../data/optimised_trajectories_ATR100.parquet"

# "../data/filed_aCCF_comparison_EAGWP100_[150, 350].parquet")

df = pd.read_parquet(f)

In [114]:
df.dtypes

waypoint                         int64
flight_id                        int64
typecode                           str
timestamp               datetime64[ns]
time                    datetime64[ns]
latitude                       float64
longitude                      float64
fl                               int64
altitude_ft                    float64
pressure                       float64
true_airspeed                  float64
mach                           float64
air_temperature                float32
specific_humidity              float32
u_wind                         float32
v_wind                         float32
geopotential                   float32
potential_vorticity            float32
relative_humidity              float32
aCCF_O3                        float32
aCCF_CH4                       float64
aCCF_NOx                       float64
aCCF_H2O                       float32
aCCF_CO2                       float64
aircraft_mass                  float64
fuel_flow                      float64
fuel_burn                      float64
engine_efficiency              float64
altitude                       float64
level                          float64
air_pressure                   float64
segment_length                 float64
thrust_setting                 float64
nox_ei                         float64
nvpm_ei_m                      float64
nvpm_ei_n                      float64
co2                            float64
nox                            float64
h2o                            float64
nvpm_mass                      float64
nvpm_number                    float64
rh                             float64
sac                            float64
ef                             float64
contrail_age           timedelta64[ns]
CiC                            float64
CoCiP                          float64
O3                             float64
CH4                            float64
NOx                            float64
H2O                            float64
CO2_with_aCCF                  float64
CO2                            float64
day                              int64
fir                                str
fl_diff                          int64
deviation                         bool
is_excluded                       bool
dtype: object

In [115]:
df

,waypoint,flight_id,typecode,timestamp,time,latitude,longitude,fl,altitude_ft,pressure,...,CH4,NOx,H2O,CO2_with_aCCF,CO2,day,fir,fl_diff,deviation,is_excluded
0,1,702,A333,2023-09-02 19:45:00,2023-09-02 19:45:00,51.464792,-0.482314,1,100.0,1009.591776,...,0.000000,0.000000,0.000000,300.691880,835.698843,4,EGTT,0,False,False
1,2,702,A333,2023-09-02 19:46:00,2023-09-02 19:46:00,51.451971,-0.420505,21,2100.0,938.643083,...,-216.164613,3750.595851,14.039114,311.486938,865.701041,4,EGTT,0,False,False
2,3,702,A333,2023-09-02 19:47:00,2023-09-02 19:47:00,51.431902,-0.361463,41,4100.0,871.786772,...,-186.304325,2991.898597,15.185856,290.112734,806.296717,4,EGTT,0,False,False
3,4,702,A333,2023-09-02 19:48:00,2023-09-02 19:48:00,51.372274,-0.390776,62,6200.0,805.791820,...,-182.648637,2797.940699,14.862731,280.931198,780.778906,4,EGTT,0,False,False
4,5,702,A333,2023-09-02 19:49:00,2023-09-02 19:49:00,51.306960,-0.444349,88,8800.0,729.749172,...,-177.043432,2434.033806,13.463100,274.712188,763.494702,4,EGTT,0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1370982,394,2813,A333,2023-12-21 09:48:00,2023-12-21 09:48:00,40.200219,-3.470401,54,5400.0,830.437744,...,-2.059471,34.018793,1.228065,23.325496,64.827456,7,NaN,0,False,False
1370983,395,2813,A333,2023-12-21 09:49:00,2023-12-21 09:49:00,40.261213,-3.489742,45,4500.0,858.890382,...,-2.117042,35.344967,1.284790,23.522003,65.373601,7,NaN,0,False,False
1370984,396,2813,A333,2023-12-21 09:50:00,2023-12-21 09:50:00,40.319544,-3.508239,35,3500.0,891.424971,...,-2.181952,37.392440,1.264995,23.740346,65.980429,7,NaN,0,False,False
1370985,397,2813,A333,2023-12-21 09:51:00,2023-12-21 09:51:00,40.373377,-3.525271,31,3100.0,904.714958,...,-3.946227,67.866079,2.283060,42.492701,118.097970,7,NaN,0,False,False
1370986,398,2813,A333,2023-12-21 09:52:47,2023-12-21 09:52:47,40.463083,-3.553894,20,2000.0,942.091776,...,NaN,NaN,NaN,NaN,NaN,7,NaN,0,False,False

In [ ]:
def generate_column_description(df: pd.DataFrame) -> pd.DataFrame:
    desc_df = pd.DataFrame({
        "short_name": df.columns,
        "long_name": "",
        "unit": "",
        "comment": "",
    })
    return desc_df

f = "../data/filed_meta.parquet"
df = pd.read_parquet(f)
# generate_column_description(df).to_csv("../docs/meta.csv", index=False)

f = "../data/filed_trajectories_EAGWP100.parquet"
df = pd.read_parquet(f)
# generate_column_description(df).to_csv("../docs/trajectory.csv", index=False)

In [103]:
df.fuel_use.sum()

np.float64(121375168.93910998)

In [93]:
df.groupby("flight_id")[["co2", "CO2", "NOx", "CoCiP"]].sum() / 1e3

                  co2         CO2         NOx       CoCiP
flight_id
0          228.653416  228.653416  179.006759   10.624837
1          277.582473  277.582473  130.794033   89.148487
2          281.924066  281.924066  169.622432  125.908637
3          247.158777  247.158777  142.213913   58.749886
4          348.774115  348.774115  140.241887 -146.412450
...               ...         ...         ...         ...
4107       244.480808  244.480808  119.558543  239.479339
4108        15.803248   15.803248   24.764768    0.000000
4109        28.057740   28.057740   17.068495  161.920338
4110        17.791307   17.791307   11.646428  105.949039
4111        19.127339   19.127339   16.149068   89.157821

[4112 rows x 4 columns]

In [94]:
df.columns

Index(['waypoint', 'flight_id', 'typecode', 'timestamp', 'time', 'latitude',
       'longitude', 'fl', 'altitude_ft', 'pressure', 'true_airspeed', 'mach',
       'air_temperature', 'specific_humidity', 'u_wind', 'v_wind',
       'geopotential', 'potential_vorticity', 'relative_humidity', 'aCCF_O3',
       'aCCF_CH4', 'aCCF_NOx', 'aCCF_H2O', 'aCCF_CO2', 'aircraft_mass',
       'fuel_flow', 'fuel_burn', 'engine_efficiency', 'altitude', 'level',
       'air_pressure', 'segment_length', 'thrust_setting', 'nox_ei',
       'nvpm_ei_m', 'nvpm_ei_n', 'co2', 'nox', 'h2o', 'nvpm_mass',
       'nvpm_number', 'rh', 'sac', 'ef', 'contrail_age', 'CiC', 'CoCiP', 'O3',
       'CH4', 'NOx', 'H2O', 'CO2_with_aCCF', 'CO2', 'day', 'fir', 'fl_diff',
       'deviation', 'is_excluded'],
      dtype='str')

In [ ]:
# dff = pd.read_parquet("../data/filed_trajectories_ATR100.parquet")
# fleetf = Fleet(data=dff)

Fleet contains 4112 flights

In [ ]:
# run once for filed, and once for optimised
# DONE June 15, 2026

# f = "../data/optimised_trajectories_ATR100.parquet"
# df = pd.read_parquet(f)

# PATR100_spec_CO2 = 5.148e-16
# cols = ["CiC", "CoCiP", "O3", "CH4", "NOx", "H2O", "CO2_with_aCCF"]#, "CO2"]
# for col in cols:
#     df[col] = df[col] / PATR100_spec_CO2 # kgCO2e

# df["CO2"] = df["co2"] # kgCO2

# df.to_parquet(f)

In [80]:
df.groupby("flight_id")[cols + ["CO2"]].sum()[["CO2", "CoCiP", "NOx", "H2O"]] / 1e3

                  CO2       CoCiP         NOx        H2O
flight_id
0          225.633659   36.663564  175.441403   8.558193
1          275.699601  170.593572  127.937969  15.540918
2          279.959819  206.341580  166.980349   9.222890
3          244.397575  148.447447  138.881816   8.726977
4          346.785512 -147.666880  138.202159  17.096793
...               ...         ...         ...        ...
4107       243.758447  266.131882  118.245558   8.407992
4108        15.675799   49.065663   17.419889   0.380142
4109        28.162708  161.868543   17.119903   0.735242
4110        17.433238  277.739637   11.914617   0.665127
4111        18.836517  111.197482   15.791253   0.468828

[4112 rows x 4 columns]

In [81]:
df.columns

Index(['waypoint', 'flight_id', 'typecode', 'timestamp', 'time', 'latitude',
       'longitude', 'fl', 'altitude_ft', 'pressure', 'true_airspeed', 'mach',
       'air_temperature', 'specific_humidity', 'u_wind', 'v_wind',
       'geopotential', 'potential_vorticity', 'relative_humidity', 'aCCF_O3',
       'aCCF_CH4', 'aCCF_NOx', 'aCCF_H2O', 'aCCF_CO2', 'aircraft_mass',
       'fuel_flow', 'fuel_burn', 'engine_efficiency', 'altitude', 'level',
       'air_pressure', 'segment_length', 'thrust_setting', 'nox_ei',
       'nvpm_ei_m', 'nvpm_ei_n', 'co2', 'nox', 'h2o', 'nvpm_mass',
       'nvpm_number', 'rh', 'sac', 'ef', 'contrail_age', 'CiC', 'CoCiP', 'O3',
       'CH4', 'NOx', 'H2O', 'CO2_with_aCCF', 'CO2', 'day', 'fir', 'fl_diff',
       'deviation', 'is_excluded'],
      dtype='str')

In [71]:
df[["co2", "CO2"]]

                co2       CO2
0        835.698843  0.835699
1        865.701041  0.865701
2        806.296717  0.806297
3        780.778906  0.780779
4        763.494702  0.763495
...             ...       ...
1370982   64.827456  0.064827
1370983   65.373601  0.065374
1370984   65.980429  0.065980
1370985  118.097970  0.118098
1370986         NaN       NaN

[1370987 rows x 2 columns]

In [63]:
co2_123 = df.query("flight_id == 123")["co2"].sum() / 1e3 # tCO2

f_gwp_atr = 0.3223 / 46.5486
print(f_gwp_atr)

print(8.8e-14 * f_gwp_atr / PATR100_spec_CO2)

print(co2_123, "tCO2")
co2_123 * 8.8e-14 * f_gwp_atr / PATR100_spec_CO2

0.00692394615520123
1.1835805393506376
29.60007847597492 tCO2

np.float64(35.03407684741559)

In [65]:
co2_123 = df.query("flight_id == 123")["co2"].sum() / 1e3 # tCO2

f_gwp_atr = 0.3223 / 46.5486
print(f_gwp_atr)

print(7.435e-14 * f_gwp_atr / PATR100_spec_CO2)

print(co2_123, "tCO2")
co2_123 * 7.435e-14 * f_gwp_atr / PATR100_spec_CO2

0.00692394615520123
0.9999910579627262
29.60007847597492 tCO2

np.float64(29.59981379096988)

In [48]:
df["CO2"] * 1e3

0           989.116887
1          1024.626906
2           954.317103
3           924.114719
4           903.657472
              ...
1370982      76.728515
1370983      77.374922
1370984      78.093152
1370985     139.778459
1370986            NaN
Name: CO2, Length: 1370987, dtype: float64

In [36]:
df[["co2", "CO2"]]

                co2       CO2
0        835.698843  0.989117
1        865.701041  1.024627
2        806.296717  0.954317
3        780.778906  0.924115
4        763.494702  0.903657
...             ...       ...
1370982   64.827456  0.076729
1370983   65.373601  0.077375
1370984   65.980429  0.078093
1370985  118.097970  0.139778
1370986         NaN       NaN

[1370987 rows x 2 columns]

In [64]:
df.groupby("flight_id")[cols + ["co2"]].sum()[["co2", "CO2", "CoCiP", "NOx"]]

                     co2         CO2       CoCiP         NOx
flight_id
0          225633.659204  267.055608   36.663564  175.441403
1          275699.601462  326.312683  170.593572  127.937969
2          279959.818853  331.354993  206.341580  166.980349
3          244397.574702  289.264213  148.447447  138.881816
4          346785.512296  410.448584 -147.666880  138.202159
...                  ...         ...         ...         ...
4107       243758.446636  288.507754  266.131882  118.245558
4108        15675.798984   18.553571   49.065663   17.419889
4109        28162.708164   33.332833  161.868543   17.119903
4110        17433.238494   20.633642  277.739637   11.914617
4111        18836.516697   22.294535  111.197482   15.791253

[4112 rows x 4 columns]

In [16]:
df["co2eq_gwp_pulse_100_co2"] + df["co2eq_gwp_pulse_100_contrails"]

0       281332.298920
1       549008.772224
2       636143.027155
3       494351.244100
4        80675.575501
            ...
4107    728561.706596
4108     98851.358246
4109    314685.110537
4110    488315.267599
4111    203476.899473
Length: 4112, dtype: float64